/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InvestigationRouteImport } from './routes/investigation'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WhitelistRouteImport } from './routes/whitelist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationRoute = InvestigationRouteImport.update({
  id: '/investigation',
  path: '/investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WhitelistRoute = WhitelistRouteImport.update({
  id: '/whitelist',
  path: '/whitelist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/investigation': typeof InvestigationRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/whitelist': typeof WhitelistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/investigation': typeof InvestigationRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/whitelist': typeof WhitelistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/investigation': typeof InvestigationRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/whitelist': typeof WhitelistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/investigation'
    | '/reports'
    | '/settings'
    | '/timeline'
    | '/whitelist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/investigation'
    | '/reports'
    | '/settings'
    | '/timeline'
    | '/whitelist'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/investigation'
    | '/reports'
    | '/settings'
    | '/timeline'
    | '/whitelist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DashboardRoute: typeof DashboardRoute
  InvestigationRoute: typeof InvestigationRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  WhitelistRoute: typeof WhitelistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation': {
      id: '/investigation'
      path: '/investigation'
      fullPath: '/investigation'
      preLoaderRoute: typeof InvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitelist': {
      id: '/whitelist'
      path: '/whitelist'
      fullPath: '/whitelist'
      preLoaderRoute: typeof WhitelistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DashboardRoute: DashboardRoute,
  InvestigationRoute: InvestigationRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  WhitelistRoute: WhitelistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
