"""
SatoshiTrace Section 91 CrPC / Section 69B IT Act Legal Notice Generator
Generates statutory notices to crypto exchanges (WazirX, CoinDCX, Binance) to freeze suspect off-ramps.
"""

import time

def generate_section_91_crpc_notice(case_id, suspect_wallet, exchange_name, txid_list, investigator_name="Investigating Officer, Cyber Crime Division"):
    """
    Generates formatted legal notice text ready for service under Section 91 of the Code of Criminal Procedure, 1973.
    """
    date_str = time.strftime("%d-%B-%Y", time.localtime())
    
    notice_text = f"""
================================================================================
           OFFICE OF THE SUPERINTENDENT OF POLICE / CYBER CRIME CELL
                       GOVERNMENT OF INDIA / STATE LEA
================================================================================

NOTICE UNDER SECTION 91 OF THE CODE OF CRIMINAL PROCEDURE, 1973
READ WITH SECTION 69B & 79(3)(b) OF THE INFORMATION TECHNOLOGY ACT, 2000

To:
The Nodal / Grievance Officer & Compliance Department,
{exchange_name}

Case Reference ID : {case_id}
Date of Issuance  : {date_str}
Investigating Off : {investigator_name}

SUBJECT: URGENT STATUTORY REQUISITION FOR FREEZING OF VIRTUAL DIGITAL ASSET 
         ACCOUNT AND PROVISION OF KYC RECORDS LINKED TO SUSPECT WALLET

WHEREAS, an investigation is in progress regarding illicit cyber extortion / ransomware / 
unauthorized financial diversion of funds involving Bitcoin blockchain transactions.

AND WHEREAS, forensic intelligence generated by SatoshiTrace (Cryptographic Verification 
Standard) has established that the following suspect wallet address has routed proceeds 
of cybercrime directly into your platform's deposit/settlement hub:

    SUSPECT WALLET ADDRESS : {suspect_wallet}
    ASSOCIATED TXIDs       : {', '.join(txid_list[:5]) if txid_list else 'Multiple Ingested Hashes'}

YOU ARE HEREBY DIRECTED AND REQUISITIONED TO FORTHWITH:

1. FREEZE / SUSPEND: Immediately place a debit and withdrawal freeze on all accounts, 
   wallets, and linked fiat accounts associated with the aforementioned address.

2. PROVIDE KYC PARTICULARS: Furnish certified true copies of:
   a. Full Legal Name, Government ID (Aadhaar / PAN / Passport), and registered mobile.
   b. Linked Bank Account details, UPI VPA, and IFSC codes.
   c. Complete fiat withdrawal and internal transfer ledger for the last 90 days.
   d. IP address login access logs with timestamp and port numbers.

PLEASE NOTE: Non-compliance with this statutory requisition attracts penal consequences 
under Section 175 and Section 188 of the Indian Penal Code (IPC) / Bharatiya Nyaya Sanhita (BNS).

Given under my hand and official seal,

{investigator_name}
Cyber Crime Police Station / Financial Intelligence Taskforce
================================================================================
"""
    return notice_text.strip()
